import { Button } from "std-widgets.slint";

global BombField := {
    property <int> row: 9;
    property <int> col: 9;
    property <[string]> list;
}

BombTile := Rectangle {
    callback clicked <=> bn.clicked;

    property <string> label;
    property <bool> is-revealed;
    property <bool> is-blank;
    property <bool> is-bomb;
    property <int> index;

    clip: true;
    height: 50px;
    width: 50px;
    border-radius: 8px;
    background: is-revealed ? #34CE57 : #3960D5;
    animate background { duration: 800ms; }

    bn := Button {
        text: label;

        clicked => { 
            if (!is-revealed) {
                is-revealed = true;
            }
        }
    }

    // curtain
    Rectangle {
        border-radius: 8px;
        background: #193076;
        width: is-revealed ? 0px : parent.width;
        height: parent.height;
        animate width { duration: 100ms; easing: ease-in; }
    }
}

export App := Window {
    title: "💣 Bombfield";

    property <int>          bombfield-col <=> BombField.col;
    property <int>          bombfield-row <=> BombField.row;
    property <[string]>     bombfield-list <=> BombField.list;

    property <bool>         disable-tiles;
    property <length>       tile-size: 50px;
    property <length>       tile-spacing: 5px;
    property <int>          current-index: -1;

    // "column_count + 1" and "row_count + 1" are the number of gaps between the tiles.
    width: (BombField.col * tile-size) + ((BombField.col + 1) * tile-spacing);
    height: (BombField.row * tile-size) + ((BombField.row + 1) * tile-spacing);

    for tile[i] in (bombfield-row*bombfield-col): BombTile {
        x: tile-spacing + mod(i, bombfield-col) * (tile-size + tile-spacing);
        y: tile-spacing + floor(i / bombfield-row) * (tile-size + tile-spacing);
        width: tile-size;
        height: tile-size;
        index: i;
        label: root.bombfield-list[i];
    }
}